#
# في هذا الملف ستجد كل المتغيرات التي تتحكم في إعدادات المدونة، شخصّها على حسب متطلباتك
#

# اسم المدونة الذي سيظهر في الأعلى
name: علي العوهلي

# وصف قصير للمدونة والذي سيظهر تحت اسمها وكجزء من عنوان المدونة في محركات البحث
description: محاولة لإثراء المحتوى العربي

# رابط صورة المدونة
# لإستخدام صورة هويتك في GitHub ضع https://github.com/<اسم_المستخدم>.png في المتغير، مثلا لهويتي الشخصية أستخدم:
# avatar: https://github.com/a3ammar.png
# ولإخفاء الصورة نهائيًا احذف الرابط من المتغير
avatar: https://github.com/alioh.png

#
# المتغيرات الآتية هي خيارية، عدل عليها إذا أردت تخصيص أكثر للمدونة
#

# لكل هوية تضعها هنا ستظهر أيقونة في أسفل المدونة
footer-links:
  webpage: http://alioh.com
  telegram: aliohali
  dribbble:
  email:
  facebook:
  flickr:
  github: alioh
  instagram: alioh
  linkedin: alioh
  pinterest:
  rss: 0 # ضع أي قيمة هنا لتظهر أيقونة RSS
  twitter: alioh
  stackoverflow: # هويتك في stackoverflow مثلا: "users/50476/bart-kiers"
  youtube: # إما channel/<عنوان_قناتك_الطويل> أو user/<اسم-مستخدمك>
  googleplus: # رقم التعريف عندما تزور هويتك (كل ما يتبع plus.google.com/)


# ضع الاسم Disqus القصير الخاص بك (الاسم القصير وليس اسم المستخدم) لتفعيل الردود على المدونة
# ستجد الاسم القصير الخاص بك في إعدادات حسابك في Disqus
disqus: 

# إذا أردت تفعيل إحصاءات الزوار في Google Analytics أدخل المعرف الخاص بك (مثلاً UA-2110908-2)
google_analytics: UA-134016492-1

# عنوان موقعك مثلاً http://barryclark.github.io
# يستخدم هذا المتغير في الـRSS والـSitemap.xml
url: https://alioh.github.io

# إذا كانت المدونة خاصة للصفحات المشاريع في GitHub (http://yourusername.github.io/repository-name مثلاً) عدل هذا المتغير ليطابق اسم المشروع
baseurl: ""

# comments:
#   provider: "staticman"
#   allowedFields: ["name", "email", "url", "message"]
#   branch: "master"
#   commitMessage: "New comment."
#   filename: comment-{@timestamp}
#   format: "yaml"
#   moderation: false
#   path: "_data/comments/{options.slug}"
#   requiredFields: ['name', 'email', 'message']
#   transforms:
#     email: "md5"

#
# هذه المتغيرات خاصة بـJekyll ولا أنصح بتعديلها، لذلك لا حاجة لشرحها
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
